// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: job.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_SCHEDULED   JobStatus = 2
	JobStatus_JOB_STATUS_DISPATCHED  JobStatus = 3
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 4
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 5
	JobStatus_JOB_STATUS_FAILED      JobStatus = 6
	JobStatus_JOB_STATUS_RETRY       JobStatus = 7
	JobStatus_JOB_STATUS_DEAD        JobStatus = 8
	JobStatus_JOB_STATUS_CANCELLED   JobStatus = 9
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_SCHEDULED",
		3: "JOB_STATUS_DISPATCHED",
		4: "JOB_STATUS_RUNNING",
		5: "JOB_STATUS_COMPLETED",
		6: "JOB_STATUS_FAILED",
		7: "JOB_STATUS_RETRY",
		8: "JOB_STATUS_DEAD",
		9: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_SCHEDULED":   2,
		"JOB_STATUS_DISPATCHED":  3,
		"JOB_STATUS_RUNNING":     4,
		"JOB_STATUS_COMPLETED":   5,
		"JOB_STATUS_FAILED":      6,
		"JOB_STATUS_RETRY":       7,
		"JOB_STATUS_DEAD":        8,
		"JOB_STATUS_CANCELLED":   9,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_job_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_job_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{0}
}

type Job struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CronExpr       string                 `protobuf:"bytes,3,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	Payload        []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,5,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Status         JobStatus              `protobuf:"varint,7,opt,name=status,proto3,enum=herschel.v1.JobStatus" json:"status,omitempty"`
	NextRunAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *Job) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Job) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type JobExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Attempt       int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Status        JobStatus              `protobuf:"varint,5,opt,name=status,proto3,enum=herschel.v1.JobStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobExecution) Reset() {
	*x = JobExecution{}
	mi := &file_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobExecution) ProtoMessage() {}

func (x *JobExecution) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobExecution.ProtoReflect.Descriptor instead.
func (*JobExecution) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobExecution) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobExecution) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobExecution) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *JobExecution) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *JobExecution) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *JobExecution) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type SubmitJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CronExpr       string                 `protobuf:"bytes,2,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitJobRequest) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *SubmitJobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubmitJobRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *SubmitJobRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Executions    []*JobExecution        `protobuf:"bytes,2,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobStatusResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *GetJobStatusResponse) GetExecutions() []*JobExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  JobStatus              `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=herschel.v1.JobStatus" json:"status_filter,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{6}
}

func (x *ListJobsRequest) GetStatusFilter() JobStatus {
	if x != nil {
		return x.StatusFilter
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{7}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_job_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{8}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_job_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{9}
}

func (x *CancelJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListDeadJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadJobsRequest) Reset() {
	*x = ListDeadJobsRequest{}
	mi := &file_job_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadJobsRequest) ProtoMessage() {}

func (x *ListDeadJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadJobsRequest.ProtoReflect.Descriptor instead.
func (*ListDeadJobsRequest) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{10}
}

func (x *ListDeadJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDeadJobsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListDeadJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadJobsResponse) Reset() {
	*x = ListDeadJobsResponse{}
	mi := &file_job_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadJobsResponse) ProtoMessage() {}

func (x *ListDeadJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadJobsResponse.ProtoReflect.Descriptor instead.
func (*ListDeadJobsResponse) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{11}
}

func (x *ListDeadJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListDeadJobsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RetryDeadJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDeadJobRequest) Reset() {
	*x = RetryDeadJobRequest{}
	mi := &file_job_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDeadJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDeadJobRequest) ProtoMessage() {}

func (x *RetryDeadJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDeadJobRequest.ProtoReflect.Descriptor instead.
func (*RetryDeadJobRequest) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{12}
}

func (x *RetryDeadJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type RetryDeadJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDeadJobResponse) Reset() {
	*x = RetryDeadJobResponse{}
	mi := &file_job_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDeadJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDeadJobResponse) ProtoMessage() {}

func (x *RetryDeadJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDeadJobResponse.ProtoReflect.Descriptor instead.
func (*RetryDeadJobResponse) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{13}
}

func (x *RetryDeadJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_job_proto protoreflect.FileDescriptor

const file_job_proto_rawDesc = "" +
	"\n" +
	"\tjob.proto\x12\vherschel.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcron_expr\x18\x03 \x01(\tR\bcronExpr\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1f\n" +
	"\vmax_retries\x18\x05 \x01(\x05R\n" +
	"maxRetries\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.herschel.v1.JobStatusR\x06status\x12:\n" +
	"\vnext_run_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb9\x02\n" +
	"\fJobExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.herschel.v1.JobStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xa7\x01\n" +
	"\x10SubmitJobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tcron_expr\x18\x02 \x01(\tR\bcronExpr\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"7\n" +
	"\x11SubmitJobResponse\x12\"\n" +
	"\x03job\x18\x01 \x01(\v2\x10.herschel.v1.JobR\x03job\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"u\n" +
	"\x14GetJobStatusResponse\x12\"\n" +
	"\x03job\x18\x01 \x01(\v2\x10.herschel.v1.JobR\x03job\x129\n" +
	"\n" +
	"executions\x18\x02 \x03(\v2\x19.herschel.v1.JobExecutionR\n" +
	"executions\"\x83\x01\n" +
	"\x0fListJobsRequest\x12;\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x16.herschel.v1.JobStatusR\fstatusFilter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"`\n" +
	"\x10ListJobsResponse\x12$\n" +
	"\x04jobs\x18\x01 \x03(\v2\x10.herschel.v1.JobR\x04jobs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"7\n" +
	"\x11CancelJobResponse\x12\"\n" +
	"\x03job\x18\x01 \x01(\v2\x10.herschel.v1.JobR\x03job\"J\n" +
	"\x13ListDeadJobsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"d\n" +
	"\x14ListDeadJobsResponse\x12$\n" +
	"\x04jobs\x18\x01 \x03(\v2\x10.herschel.v1.JobR\x04jobs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\",\n" +
	"\x13RetryDeadJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\":\n" +
	"\x14RetryDeadJobResponse\x12\"\n" +
	"\x03job\x18\x01 \x01(\v2\x10.herschel.v1.JobR\x03job*\x82\x02\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14JOB_STATUS_SCHEDULED\x10\x02\x12\x19\n" +
	"\x15JOB_STATUS_DISPATCHED\x10\x03\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x04\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x05\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x06\x12\x14\n" +
	"\x10JOB_STATUS_RETRY\x10\a\x12\x13\n" +
	"\x0fJOB_STATUS_DEAD\x10\b\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\t2\xec\x03\n" +
	"\n" +
	"JobService\x12J\n" +
	"\tSubmitJob\x12\x1d.herschel.v1.SubmitJobRequest\x1a\x1e.herschel.v1.SubmitJobResponse\x12S\n" +
	"\fGetJobStatus\x12 .herschel.v1.GetJobStatusRequest\x1a!.herschel.v1.GetJobStatusResponse\x12G\n" +
	"\bListJobs\x12\x1c.herschel.v1.ListJobsRequest\x1a\x1d.herschel.v1.ListJobsResponse\x12J\n" +
	"\tCancelJob\x12\x1d.herschel.v1.CancelJobRequest\x1a\x1e.herschel.v1.CancelJobResponse\x12S\n" +
	"\fListDeadJobs\x12 .herschel.v1.ListDeadJobsRequest\x1a!.herschel.v1.ListDeadJobsResponse\x12S\n" +
	"\fRetryDeadJob\x12 .herschel.v1.RetryDeadJobRequest\x1a!.herschel.v1.RetryDeadJobResponseBCZAgithub.com/ardeez/distributed-job-scheduler/internal/transport/pbb\x06proto3"

var (
	file_job_proto_rawDescOnce sync.Once
	file_job_proto_rawDescData []byte
)

func file_job_proto_rawDescGZIP() []byte {
	file_job_proto_rawDescOnce.Do(func() {
		file_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)))
	})
	return file_job_proto_rawDescData
}

var file_job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_job_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_job_proto_goTypes = []any{
	(JobStatus)(0),                // 0: herschel.v1.JobStatus
	(*Job)(nil),                   // 1: herschel.v1.Job
	(*JobExecution)(nil),          // 2: herschel.v1.JobExecution
	(*SubmitJobRequest)(nil),      // 3: herschel.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),     // 4: herschel.v1.SubmitJobResponse
	(*GetJobStatusRequest)(nil),   // 5: herschel.v1.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),  // 6: herschel.v1.GetJobStatusResponse
	(*ListJobsRequest)(nil),       // 7: herschel.v1.ListJobsRequest
	(*ListJobsResponse)(nil),      // 8: herschel.v1.ListJobsResponse
	(*CancelJobRequest)(nil),      // 9: herschel.v1.CancelJobRequest
	(*CancelJobResponse)(nil),     // 10: herschel.v1.CancelJobResponse
	(*ListDeadJobsRequest)(nil),   // 11: herschel.v1.ListDeadJobsRequest
	(*ListDeadJobsResponse)(nil),  // 12: herschel.v1.ListDeadJobsResponse
	(*RetryDeadJobRequest)(nil),   // 13: herschel.v1.RetryDeadJobRequest
	(*RetryDeadJobResponse)(nil),  // 14: herschel.v1.RetryDeadJobResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_job_proto_depIdxs = []int32{
	0,  // 0: herschel.v1.Job.status:type_name -> herschel.v1.JobStatus
	15, // 1: herschel.v1.Job.next_run_at:type_name -> google.protobuf.Timestamp
	15, // 2: herschel.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: herschel.v1.Job.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: herschel.v1.JobExecution.status:type_name -> herschel.v1.JobStatus
	15, // 5: herschel.v1.JobExecution.started_at:type_name -> google.protobuf.Timestamp
	15, // 6: herschel.v1.JobExecution.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 7: herschel.v1.SubmitJobResponse.job:type_name -> herschel.v1.Job
	1,  // 8: herschel.v1.GetJobStatusResponse.job:type_name -> herschel.v1.Job
	2,  // 9: herschel.v1.GetJobStatusResponse.executions:type_name -> herschel.v1.JobExecution
	0,  // 10: herschel.v1.ListJobsRequest.status_filter:type_name -> herschel.v1.JobStatus
	1,  // 11: herschel.v1.ListJobsResponse.jobs:type_name -> herschel.v1.Job
	1,  // 12: herschel.v1.CancelJobResponse.job:type_name -> herschel.v1.Job
	1,  // 13: herschel.v1.ListDeadJobsResponse.jobs:type_name -> herschel.v1.Job
	1,  // 14: herschel.v1.RetryDeadJobResponse.job:type_name -> herschel.v1.Job
	3,  // 15: herschel.v1.JobService.SubmitJob:input_type -> herschel.v1.SubmitJobRequest
	5,  // 16: herschel.v1.JobService.GetJobStatus:input_type -> herschel.v1.GetJobStatusRequest
	7,  // 17: herschel.v1.JobService.ListJobs:input_type -> herschel.v1.ListJobsRequest
	9,  // 18: herschel.v1.JobService.CancelJob:input_type -> herschel.v1.CancelJobRequest
	11, // 19: herschel.v1.JobService.ListDeadJobs:input_type -> herschel.v1.ListDeadJobsRequest
	13, // 20: herschel.v1.JobService.RetryDeadJob:input_type -> herschel.v1.RetryDeadJobRequest
	4,  // 21: herschel.v1.JobService.SubmitJob:output_type -> herschel.v1.SubmitJobResponse
	6,  // 22: herschel.v1.JobService.GetJobStatus:output_type -> herschel.v1.GetJobStatusResponse
	8,  // 23: herschel.v1.JobService.ListJobs:output_type -> herschel.v1.ListJobsResponse
	10, // 24: herschel.v1.JobService.CancelJob:output_type -> herschel.v1.CancelJobResponse
	12, // 25: herschel.v1.JobService.ListDeadJobs:output_type -> herschel.v1.ListDeadJobsResponse
	14, // 26: herschel.v1.JobService.RetryDeadJob:output_type -> herschel.v1.RetryDeadJobResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_job_proto_init() }
func file_job_proto_init() {
	if File_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_proto_goTypes,
		DependencyIndexes: file_job_proto_depIdxs,
		EnumInfos:         file_job_proto_enumTypes,
		MessageInfos:      file_job_proto_msgTypes,
	}.Build()
	File_job_proto = out.File
	file_job_proto_goTypes = nil
	file_job_proto_depIdxs = nil
}
